# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adicionar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(750, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMaximumSize(QtCore.QSize(750, 500))
        mainWindow.setToolTip("")
        mainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setStyleSheet("alternate-background-color: qconicalgradient(cx:0.189, cy:0, angle:128.7, stop:0 rgba(255, 255, 0, 69), stop:0.353234 rgba(138, 71, 255, 130), stop:0.41791 rgba(121, 0, 255, 255), stop:0.467662 rgba(255, 0, 0, 234), stop:0.472637 rgba(55, 0, 255, 208), stop:1 rgba(255, 255, 0, 69));\n"
"\n"
"background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("\n"
"selection-background-color: qconicalgradient(cx:0.189, cy:0, angle:128.7, stop:0 rgba(255, 255, 0, 69), stop:0.353234 rgba(138, 71, 255, 130), stop:0.41791 rgba(121, 0, 255, 255), stop:0.467662 rgba(255, 0, 0, 234), stop:0.472637 rgba(55, 0, 255, 208), stop:1 rgba(255, 255, 0, 69));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setEnabled(True)
        self.label.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255)),qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255));\n"
"color:rgb(255, 255, 255)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255)),qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255));")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255)),qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255));\n"
"color:rgb(255, 255, 255)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_5.addWidget(self.checkBox, 3, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox = QtWidgets.QComboBox(self.frame_7)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_6.addWidget(self.comboBox, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setEnabled(False)
        self.label_5.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.frame_7)
        self.spinBox.setEnabled(False)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_6.addWidget(self.spinBox, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.frame_7, 3, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setMaximumSize(QtCore.QSize(10, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 3, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_6)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.dateTimeEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_4.addWidget(self.dateTimeEdit, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setEnabled(True)
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setStyleSheet("background-color: rgb(40, 101, 157);\n"
"color:rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255)),qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255));\n"
"color:rgb(255, 255, 255)")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_6, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_5, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.frame_3, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStyleSheet("background-color: rgb(40, 101, 157);\n"
"color:rgb(255, 255, 255)")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "ADICIONAR"))
        self.label.setText(_translate("mainWindow", "ADICIONAR TAREFA"))
        self.label_2.setText(_translate("mainWindow", "nova tarefa:"))
        self.checkBox.setText(_translate("mainWindow", "LEMBRETE RECORENTE"))
        self.comboBox.setItemText(0, _translate("mainWindow", "dias"))
        self.comboBox.setItemText(1, _translate("mainWindow", "horas"))
        self.comboBox.setItemText(2, _translate("mainWindow", "semanas"))
        self.comboBox.setItemText(3, _translate("mainWindow", "meses"))
        self.label_5.setText(_translate("mainWindow", "intervalo:"))
        self.label_4.setText(_translate("mainWindow", "ou"))
        self.label_6.setText(_translate("mainWindow", "/"))
        self.pushButton.setText(_translate("mainWindow", "personalizado"))
        self.label_3.setText(_translate("mainWindow", "Nova data:"))
