# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ATUALIZADATA.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(272, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.frame1 = QtWidgets.QFrame(self.frame)
        self.frame1.setEnabled(True)
        self.frame1.setMinimumSize(QtCore.QSize(0, 0))
        self.frame1.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame1.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))")
        self.frame1.setObjectName("frame1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame1)
        self.pushButton_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setAutoRepeat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame1)
        self.pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setAutoRepeat(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame1, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("background-color: rgb(40, 101, 157);\n"
"color:rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame_5.setFont(font)
        self.frame_5.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(66, 147, 200, 255);\n"
"color: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 2)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setEnabled(True)
        self.frame_4.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox = QtWidgets.QComboBox(self.frame_7)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_6.addWidget(self.comboBox, 0, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.frame_7)
        self.spinBox.setEnabled(False)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_6.addWidget(self.spinBox, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setEnabled(False)
        self.label_5.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_7, 1, 0, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_4.setStyleSheet("background-color: rgb(40, 101, 157);\n"
"color:rgb(255, 255, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_4)
        self.dateTimeEdit.setEnabled(False)
        self.dateTimeEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))")
        self.dateTimeEdit.setKeyboardTracking(False)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_5.addWidget(self.dateTimeEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMaximumSize(QtCore.QSize(10, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "APAGAR"))
        self.pushButton.setText(_translate("MainWindow", "SALVAR"))
        self.pushButton_3.setText(_translate("MainWindow", "Voltar"))
        self.label_2.setText(_translate("MainWindow", "agendado para: "))
        self.label_3.setText(_translate("MainWindow", "00/00/0000"))
        self.comboBox.setItemText(0, _translate("MainWindow", "dias"))
        self.comboBox.setItemText(1, _translate("MainWindow", "horas"))
        self.comboBox.setItemText(2, _translate("MainWindow", "semanas"))
        self.comboBox.setItemText(3, _translate("MainWindow", "meses"))
        self.label_5.setText(_translate("MainWindow", "intervalo:"))
        self.pushButton_4.setText(_translate("MainWindow", "personalizado"))
        self.label_4.setText(_translate("MainWindow", "NOVA DATA:"))
        self.label.setText(_translate("MainWindow", "/"))
