# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 1677))
        MainWindow.setBaseSize(QtCore.QSize(1000, 600))
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setSizeIncrement(QtCore.QSize(1000, 600))
        self.centralwidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_5.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(944, 65, 22, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setGeometry(QtCore.QRect(130, 70, 350, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(200, 30))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.listWidget.setFont(font)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.53295, y1:0.631, x2:0.542602, y2:1, stop:0.0149254 rgba(66, 147, 200, 255),);\n"
"color:white;\n"
"font: 12pt \"Arial\";")
        self.listWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget.setAutoScroll(False)
        self.listWidget.setAutoScrollMargin(0)
        self.listWidget.setTabKeyNavigation(False)
        self.listWidget.setDragEnabled(False)
        self.listWidget.setDragDropOverwriteMode(False)
        self.listWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget.setLayoutMode(QtWidgets.QListView.Batched)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setBatchSize(200)
        self.listWidget.setWordWrap(False)
        self.listWidget.setSelectionRectVisible(True)
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 191, 24))
        self.label_2.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255))")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(280, 10, 141, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.53295, y1:0.631, x2:0.542602, y2:1, stop:0.0149254 rgba(66, 147, 200, 255),)\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_6)
        self.frame_4.setMinimumSize(QtCore.QSize(200, 100))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("background-color:qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))\n"
"qlineargradient(spread:pad,\n"
" x1:0.53295, y1:0.631, x2:0.542602, y2:1,\n"
" stop:0.0149254 rgba(66, 147, 200, 255)\n"
", stop:1 rgba(255, 255, 255, 255))")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_adicionar_tarefa = QtWidgets.QPushButton(self.frame_4)
        self.btn_adicionar_tarefa.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.btn_adicionar_tarefa.sizePolicy().hasHeightForWidth())
        self.btn_adicionar_tarefa.setSizePolicy(sizePolicy)
        self.btn_adicionar_tarefa.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_adicionar_tarefa.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_adicionar_tarefa.setFont(font)
        self.btn_adicionar_tarefa.setStyleSheet("background-color: rgb(40, 101, 157);\n"
"color:rgb(255, 255, 255)")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img_GUI/adicionar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_adicionar_tarefa.setIcon(icon)
        self.btn_adicionar_tarefa.setIconSize(QtCore.QSize(40, 50))
        self.btn_adicionar_tarefa.setCheckable(False)
        self.btn_adicionar_tarefa.setObjectName("btn_adicionar_tarefa")
        self.verticalLayout_2.addWidget(self.btn_adicionar_tarefa)
        self.btn_adicionar_tarefa_2 = QtWidgets.QPushButton(self.frame_4)
        self.btn_adicionar_tarefa_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.btn_adicionar_tarefa_2.sizePolicy().hasHeightForWidth())
        self.btn_adicionar_tarefa_2.setSizePolicy(sizePolicy)
        self.btn_adicionar_tarefa_2.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_adicionar_tarefa_2.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_adicionar_tarefa_2.setFont(font)
        self.btn_adicionar_tarefa_2.setStyleSheet("background-color: rgb(40, 101, 157);\n"
"color:rgb(255, 255, 255)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/adicionar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_adicionar_tarefa_2.setIcon(icon1)
        self.btn_adicionar_tarefa_2.setIconSize(QtCore.QSize(50, 50))
        self.btn_adicionar_tarefa_2.setCheckable(False)
        self.btn_adicionar_tarefa_2.setObjectName("btn_adicionar_tarefa_2")
        self.verticalLayout_2.addWidget(self.btn_adicionar_tarefa_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.gridLayout_3.addWidget(self.frame_6, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAd = QtWidgets.QAction(MainWindow)
        self.actionAd.setCheckable(True)
        self.actionAd.setChecked(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/vazio.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAd.setIcon(icon2)
        self.actionAd.setObjectName("actionAd")

        self.retranslateUi(MainWindow)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Agenda"))
        self.label_3.setText(_translate("MainWindow", "menu principal"))
        self.listWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.listWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.listWidget.setSortingEnabled(True)
        self.label_2.setText(_translate("MainWindow", "Para Hoje:                "))
        self.pushButton.setText(_translate("MainWindow", "Para Agora"))
        self.btn_adicionar_tarefa.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>adicionar tafefas</p></body></html>"))
        self.btn_adicionar_tarefa.setText(_translate("MainWindow", "adicionar tarefas"))
        self.btn_adicionar_tarefa_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>adicionar tafefas</p></body></html>"))
        self.btn_adicionar_tarefa_2.setText(_translate("MainWindow", "Mais opções"))
        self.actionAd.setText(_translate("MainWindow", "ad.qrc"))
