# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'date.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calendario_form(object):
    def setupUi(self, calendario_form):
        calendario_form.setObjectName("calendario_form")
        calendario_form.resize(527, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(calendario_form.sizePolicy().hasHeightForWidth())
        calendario_form.setSizePolicy(sizePolicy)
        calendario_form.setMinimumSize(QtCore.QSize(527, 391))
        calendario_form.setMaximumSize(QtCore.QSize(527, 391))
        calendario_form.setBaseSize(QtCore.QSize(473, 382))
        self.gridLayout_2 = QtWidgets.QGridLayout(calendario_form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 1)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(calendario_form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)

        self.retranslateUi(calendario_form)
        QtCore.QMetaObject.connectSlotsByName(calendario_form)

    def retranslateUi(self, calendario_form):
        _translate = QtCore.QCoreApplication.translate
        calendario_form.setWindowTitle(_translate("calendario_form", "Form"))
        self.pushButton.setText(_translate("calendario_form", "PushButton"))
